### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [sheepduke/clop#1] opened 2022-02-05 16:38 UTC
Building with SBCL 2.2.1 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 7113c1c9399f1455cffac49b9e419f548d9f8936

*clop-tests* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001B98003}>: The name "SERAPEUM" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2022-02-05/failure-report/clop.html)

**Comment by sheepduke** [comment] 2022-02-06 03:25
It was caused by an invalid reference to `serapeum` package.

Fixed in version `v1.0.1`.

**Closed as completed by sheepduke** 2022-02-06 03:25 UTC
